pipeline{
  agent any
 environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = 'us-east-2'
    }

    stages{
        stage('Checkout SCM'){
            steps{
                script{
                   checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Kishanrampure/DevOps-Terraform-EKS-Project.git']])
                }
            }
        }
       stage('Initializing Terraform'){
            steps{
                script{
                   dir('EKS'){
                    sh 'terraform init'
                   }
                }
            }
        }
        stage('Formatting Terraform'){
            steps{
                script{
                   dir('EKS'){
                    sh 'terraform fmt'
                   }
                }
            }
        }
        stage('Validating Terraform'){
            steps{
                script{
                   dir('EKS'){
                    sh 'terraform validate'
                   }
                }
            }
        }
        stage('Plan Terraform'){
            steps{
                script{
                   dir('EKS'){
                    sh 'terraform plan'
                   }
                }
            }
        }
        stage('Apply Terraform'){
            steps{
                script{
                   dir('EKS'){
                    sh 'terraform $action --auto-approve'
                   }
                }
            }
        }
        stage('Deploying Nginx'){
            steps{
                script{
                   dir('EKS'){
                    sh 'aws eks update-kubeconfig --name my-eks-cluster'
                    sh 'aws eks create-access-entry --cluster-name my-eks-cluster --principal-arn arn:aws:iam::111122223333:user/username --type STANDARD --username username'
                        sh 'kubectl apply -f nginx.yml'
                   }
                }
            }
        }
      }
}  